name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch: # Allows manual triggering

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues and PRs
        uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has been automatically marked as stale due to inactivity. It will be closed if no further activity occurs."
          stale-pr-message: "This pull request has been automatically marked as stale due to inactivity. It will be closed if no further activity occurs."
          days-before-stale: 7 # Number of days before marking as stale
          days-before-close: 3 # Number of days before closing after being marked as stale
          stale-issue-label: "stale"
          exempt-issue-labels: "keep-open" # Prevents issues with this label from being marked stale
          stale-pr-label: "stale"
          exempt-pr-labels: "keep-open"
